
// SIGNIN SIGNUP
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const LOGOUT = 'LOGOUT';

export const UPDATE_INFO = 'UPDATE_INFO';
export const UPDATE_AVATAR = 'UPDATE_AVATAR';

// DOCTORS
export const AGREGAR_DOCTOR = 'AGREGAR_DOCTOR';
export const MOSTRAR_DOCTORES = 'MOSTRAR_DOCTORES';
export const ELIMINAR_DOCTOR = 'ELIMINAR_DOCTOR';
export const EDITAR_DOCTOR = 'EDITAR_DOCTOR';
export const MOSTRAR_DOCTOR = 'MOSTRAR_DOCTOR';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';

// SPECIALITIES
export const AGREGAR_ESPECIALIDAD = 'AGREGAR_ESPECIALIDAD';
export const MOSTRAR_ESPECIALIDADES = 'MOSTRAR_ESPECIALIDADES';
export const ELIMINAR_ESPECIALIDAD = 'ELIMINAR_ESPECIALIDAD';
export const EDITAR_ESPECIALIDAD = 'EDITAR_ESPECIALIDAD';
export const MOSTRAR_ESPECIALIDAD = 'MOSTRAR_ESPECIALIDAD';
export const VALIDATE_ESPECIALIDAD = 'SUCCESSED_ESPECIALIDAD';

// PATIENTS
export const AGREGAR_PACIENTE = 'AGREGAR_PACIENTE';
export const MOSTRAR_PACIENTES = 'MOSTRAR_PACIENTES';
export const ELIMINAR_PACIENTE = 'ELIMINAR_PACIENTE';
export const EDITAR_PACIENTE = 'EDITAR_PACIENTE';
export const MOSTRAR_PACIENTE = 'MOSTRAR_PACIENTE';
export const LOADING_PATIENTS = 'LOADING_PATIENTS';
export const ERROR_PATIENTS = 'ERROR_PATIENTS';

// TURNS
export const AGREGAR_TURNO = 'AGREGAR_TURNO';
export const MOSTRAR_TURNOS = 'MOSTRAR_TURNOS';
export const ELIMINAR_TURNO = 'ELIMINAR_TURNO';
export const EDITAR_TURNO = 'EDITAR_TURNO';
export const MOSTRAR_TURNO = 'MOSTRAR_TURNO';
export const LOADING_TURNOS = 'LOADING_TURNOS';
export const ERROR_TURNOS = 'ERROR_TURNOS';

// DOCTOR TURN
export const AGREGAR_DOCTORTURN = 'AGREGAR_DOCTORTURN';
