
// SIGNIN SIGNUP
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';

export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const SIGNIN_ERROR = 'SIGNIN_ERROR';
export const LOGOUT = 'LOGOUT';

// DOCTORS
export const AGREGAR_DOCTOR = 'AGREGAR_DOCTOR';
export const MOSTRAR_DOCTORES = 'MOSTRAR_DOCTORES';
export const ELIMINAR_DOCTOR = 'ELIMINAR_DOCTOR';
export const EDITAR_DOCTOR = 'EDITAR_DOCTOR';
export const MOSTRAR_DOCTOR = 'MOSTRAR_DOCTOR';
export const LOADING = 'LOADING';
export const ERROR = 'ERROR';

// SPECIALITIES
export const AGREGAR_ESPECIALIDAD = 'AGREGAR_ESPECIALIDAD';
export const MOSTRAR_ESPECIALIDADES = 'MOSTRAR_ESPECIALIDADES';
export const ELIMINAR_ESPECIALIDAD = 'ELIMINAR_ESPECIALIDAD';
export const EDITAR_ESPECIALIDAD = 'EDITAR_ESPECIALIDAD';
export const MOSTRAR_ESPECIALIDAD = 'MOSTRAR_ESPECIALIDAD';
